runtime: python39

env_variables:
  BUCKET_ID: ibkr-report-parser
  LOGGING_LEVEL: WARNING

handlers:
  - url: /static
    static_dir: ibkr_report/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
