runtime: python39

env_variables:
  BUCKET_ID: ibkr-report-parser

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
