[build-system]
requires = ["setuptools", "wheel"]

[tool.coverage.run]
branch = true
source = ["ibkr_report"]

[tool.coverage.report]
exclude_lines = ["@(abc\\.)?abstractmethod"]

[tool.mypy]
files = ["*.py", "ibkr_report/*.py"]
